## Generate Array at given size

In [1]:
import numpy

In [2]:
x = numpy.zeros((3,4))
x

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [3]:
y = numpy.zeros(5)   
y

array([0., 0., 0., 0., 0.])

In [14]:
from numpy import ndarray
a = ndarray((5,),int)
a

array([-1038699840,         462,           0,           0,           1])

In [17]:
t = int(input(""))
xx = [5]*t
yy = [[2]*t]*t

for i in range(1, t+1):
    xx[i-1] = i;

    for j in range(1, t+1):
        yy[i-1][j-1] = j;

print(xx)
print(yy)


4
[1, 2, 3, 4]
[[1, 2, 3, 4], [1, 2, 3, 4], [1, 2, 3, 4], [1, 2, 3, 4]]


In [18]:
d = [ [ None for y in range( 2 ) ] for x in range( 2 ) ]
d

[[None, None], [None, None]]

In [23]:
d = [[ [ None ] * 2 ] * 2] * 3
d

[[[None, None], [None, None]],
 [[None, None], [None, None]],
 [[None, None], [None, None]]]

In [34]:
d[0][1][0]

0

## Swap elements in a list

In [35]:
# Swap function note the pos1 is the list[0]
def swapPositions(list, pos1, pos2):
     
    list[pos1], list[pos2] = list[pos2], list[pos1]
    return list
 
# Driver function
List = [23, 65, 19, 90]
pos1, pos2  = 1, 3
 
print(swapPositions(List, pos1-1, pos2-1))

[19, 65, 23, 90]


## sort a list

In [36]:
nums = [1, 5, 3, 4, 2, 10, 6, 8, 7, 9]
nums.sort()
print('List in Ascending Order: ', nums)

nums.sort(reverse=True)
print('List in Descending Order: ', nums)

List in Ascending Order:  [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
List in Descending Order:  [10, 9, 8, 7, 6, 5, 4, 3, 2, 1]


## list reverse

In [40]:
numlist = [1, 5, 3, 4, 2, 10, 6, 8, 7, 9]
numlist.reverse()
numlist

[9, 7, 8, 6, 10, 2, 4, 3, 5, 1]

## Rotate a list

In [41]:
test_list = [1, 4, 6, 7, 2]

In [44]:
len(test_list)

5

In [46]:
test_list[(0 + 3) % len(test_list)]

2

In [47]:
(0 + 3) % len(test_list)

3

In [43]:
# using list comprehension to left rotate by 3 steps
test_list = [test_list[(i + 3) % len(test_list)]
               for i, x in enumerate(test_list)]
test_list

[4, 6, 7, 2, 1]

In [49]:
# using list comprehension to right rotate by 3
# back to Original
test_list = [test_list[(i - 3) % len(test_list)]
               for i, x in enumerate(test_list)]
test_list

[1, 4, 6, 7, 2]

## move 0 to the end of list

In [67]:
nums = [0, 1, 0, 3, 12]
newnums = [x for x in nums if x != 0]
zeros = len(nums) - len(newnums)
newnums

[1, 3, 12]

In [69]:
for i in range(zeros):
    newnums.append(0)
    
print(newnums)

[1, 3, 12, 0, 0]


## python program to print prime factors

In [71]:
import math

def primefactors(n):
   #even number divisible
   while n % 2 == 0:
      print (2),
      n = n / 2
    
   #n became odd
   for i in range(3,int(math.sqrt(n))+1,2):
     
      while (n % i == 0):
         print (i)
         n = n / i
    
   if n > 2:
      print (n)
 
n = int(input("Enter the number for calculating the prime factors :\n"))
primefactors(n)

Enter the number for calculating the prime factors :
738
2
3
3
41.0


## Hail conjecture

In [74]:
n = int(input("Enter the number for calculating the Hail conjecture :\n"))

Enter the number for calculating the Hail conjecture :
999


In [75]:
sum = 0
while n != 1:
    if n % 2 == 0:
        n = n / 2
        sum += 1
    else:
        n = 3 * n + 1
        sum += 1
print(f"sum = {sum}")

sum = 49


## Find majority in a list

In [80]:
def find_majority(k):
    myMap = {}
    maximum = ( '', 0 ) # (occurring element, occurrences)
    print(type(maximum))
    
    for n in k:
        if n in myMap: myMap[n] += 1
        else: myMap[n] = 1

        # Keep track of maximum on the go
        if myMap[n] > maximum[1]: maximum = (n,myMap[n])

    return maximum

In [81]:
find_majority([1,2,3,4,3,3,2,4,5,6,1,2,3,4,5,1,2,3,4,6,5])

<class 'tuple'>


(3, 5)

## double factorition n!!

In [83]:
def doublefactorial(n):
     if n <= 0 :
         return 1
     else:
         return n * doublefactorial(n-2)

In [84]:
n = 9
doublefactorial(n)

945

## Implement Stack

In [85]:
list=[]
list.append(1) # append 1
print("push:",list)
list.append(2) # append 2
print("push:",list)
list.append(3) # append 3
print("push:",list)
list.pop() # pop 3
print("pop:",list)
print("peek:",list[-1]) # get top most element
list.pop() # pop 2
print("pop:",list)
print("peek:",list[-1]) # get top most element

push: [1]
push: [1, 2]
push: [1, 2, 3]
pop: [1, 2]
peek: 2
pop: [1]
peek: 1


## Queue – Linked List Implementation

In [86]:
# Python3 program to demonstrate linked list
# based implementation of queue
  
# A linked list (LL) node
# to store a queue entry
class Node:
      
    def __init__(self, data):
        self.data = data
        self.next = None
  
# A class to represent a queue
  
# The queue, front stores the front node
# of LL and rear stores the last node of LL
class Queue:
      
    def __init__(self):
        self.front = self.rear = None
  
    def isEmpty(self):
        return self.front == None
      
    # Method to add an item to the queue
    def EnQueue(self, item):
        temp = Node(item)
          
        if self.rear == None:
            self.front = self.rear = temp
            return
        self.rear.next = temp
        self.rear = temp
  
    # Method to remove an item from queue
    def DeQueue(self):
          
        if self.isEmpty():
            return
        temp = self.front
        self.front = temp.next
  
        if(self.front == None):
            self.rear = None
  
# Driver Code
if __name__== '__main__':
    q = Queue()
    q.EnQueue(10)
    q.EnQueue(20)
    q.DeQueue()
    q.DeQueue()
    q.EnQueue(30)
    q.EnQueue(40)
    q.EnQueue(50) 
    q.DeQueue()   
    print("Queue Front " + str(q.front.data))
    print("Queue Rear " + str(q.rear.data))

Queue Front 40
Queue Rear 50
