## Numpy Array Indexing

In [1]:
import numpy as np

## Basic Indexing

In [2]:
x = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
x[1:7:2] # [start_index, end_index, step] not include the last item

array([1, 3, 5])

In [33]:
x[::2] #start from begining to the end, step 2

array([0, 2, 4, 6, 8])

In [3]:
x[-2:10]

array([8, 9])

In [4]:
x[-3:3:-1]

array([7, 6, 5, 4])

In [5]:
x[5:]

array([5, 6, 7, 8, 9])

#### note x[1:10:5,::-1] can also be implemented as obj = (slice(1,10,5), slice(None,None,-1)); x[obj] .

In [9]:
y = np.array([[[1],[2],[3]], [[4],[5],[6]]])
#y = np.array([[1, 2, 3], [4, 5, 6]])
y.shape

(2, 3, 1)

In [10]:
# Notice y[1:2] == y[1] == y[1:]
y[1:2]

array([[[4],
        [5],
        [6]]])

In [15]:
y[...,0]

array([[1, 2, 3],
       [4, 5, 6]])

## Advanced Indexing

In [ ]:
#The definition of advanced indexing means that x[(1,2,3),] is fundamentally different than x[(1,2,3)]. 
#The latter is equivalent to x[1,2,3] which will trigger basic selection 
#while the former will trigger advanced indexing. 

In [16]:
x1 = np.array([[1, 2], [3, 4], [5, 6]])
x1[[0, 1, 2], [0, 1, 0]] # the [0, 1, 2] index the rows, [0, 1, 0] indexing the relavent columns

array([1, 4, 5])

In [17]:
x1[[0,1,2], ] # means take all the columns

array([[1, 2],
       [3, 4],
       [5, 6]])

In [18]:
x2 = np.array([[ 0,  1,  2],
              [ 3,  4,  5],
              [ 6,  7,  8],
              [ 9, 10, 11]])
rows = np.array([[0, 0],    # x2[[0, 0], ] means get two times x2[[0],]
                 [3, 3]], dtype=np.intp)
columns = np.array([[0, 2],
                    [0, 2]], dtype=np.intp)
x2[rows, columns]

array([[ 0,  2],
       [ 9, 11]])

In [25]:
x2[([0,0],[3, 3]), ([0,2], [0,2])]

array([[ 0,  2],
       [ 9, 11]])

In [26]:
x2[[0, 0], ]

array([[0, 1, 2],
       [0, 1, 2]])

In [29]:
x2[2:, ([0,2], [0, 2])]

array([[[ 6,  8],
        [ 6,  8]],

       [[ 9, 11],
        [ 9, 11]]])

In [30]:
x2[1:2, 1:3]

array([[4, 5]])

In [31]:
x2[1:2, [1, 2]]

array([[4, 5]])